eureka:
  instance:
    hostname: e-server-git-akshaykemekar-dev.apps.sandbox.x8i5.p1.openshiftapps.com:8761
  client:
    serviceUrl:
      defaultZone: http://e-server-git-akshaykemekar-dev.apps.sandbox.x8i5.p1.openshiftapps.com:8761/eureka/


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
